import { Image } from "expo-image";
import { useFocusEffect, useRouter } from "expo-router";
import { useCallback } from "react";
import { Share, Text, View } from "react-native";
import { track } from "../../src/analytics";
import { useAuth } from "../../src/auth";
import { useTheme } from "../../src/theme";
import { Avatar, Button, Page, Section, TextLink } from "../../src/ui";
export default function Profile() { const { api, profile, refreshProfile } = useAuth(); const { colors } = useTheme(); const router = useRouter(); useFocusEffect(useCallback(() => { void refreshProfile(); void track(api, "navigation_profile"); }, [refreshProfile, api])); const publicUrl = `https://network.artclub.wtf/${profile?.profileType === "artist" ? "artist" : "profile"}/${profile?.slug}`; return <Page>{profile?.coverImageUrl ? <Image source={profile.coverImageUrl} style={{ width: "100%", aspectRatio: 16 / 7, borderRadius: 4 }} contentFit="cover"/> : <View style={{ width: "100%", aspectRatio: 16 / 7, borderRadius: 4, backgroundColor: colors.surfaceMuted }}/>}<View style={{ alignItems: "center", gap: 7, marginTop: -42 }}><Avatar profile={profile} size={84}/><Text style={{ color: colors.text, fontSize: 26, fontWeight: "600" }}>{profile?.displayName}</Text><Text style={{ color: colors.textMuted }}>@{profile?.username} · {profile?.profileType?.replaceAll("_", " ")}</Text>{profile?.city ? <Text style={{ color: colors.textMuted }}>{profile.city}{profile.country ? `, ${profile.country}` : ""}</Text> : null}</View><View style={{ flexDirection: "row", gap: 8 }}><View style={{ flex: 1 }}><Button label="Edit profile" onPress={() => router.push("/profile/edit")}/></View><View style={{ flex: 1 }}><Button label="Share" variant="secondary" icon="share-outline" onPress={() => { void track(api, "profile_native_share"); void Share.share({ message: publicUrl }); }}/></View></View><Section title="About"><Text style={{ color: colors.text, lineHeight: 21 }}>{profile?.bio || "Add a short biography to help your network understand your practice and interests."}</Text>{profile?.disciplines?.length ? <Text style={{ color: colors.textMuted }}>{profile.disciplines.join(" · ")}</Text> : null}</Section><Section title="Profile sections"><TextLink label="Explore art" onPress={() => router.push("/explore-art")}/><TextLink label="Network updates" onPress={() => router.push("/updates")}/><TextLink label="Settings and appearance" onPress={() => router.push("/settings")}/></Section></Page>; }
