import type { ArtworkCard } from "@artclub/models";
import { Image } from "expo-image";
import { useFocusEffect, useRouter } from "expo-router";
import { useCallback, useState } from "react";
import { Pressable, RefreshControl, Text, View } from "react-native";
import { track } from "../src/analytics";
import { useAuth } from "../src/auth";
import { useTheme } from "../src/theme";
import { Empty, ErrorState, Field, Page } from "../src/ui";
export default function ExploreArt() { const { api, baseUrl } = useAuth(); const { colors } = useTheme(); const router = useRouter(); const [items, setItems] = useState<ArtworkCard[]>([]); const [q, setQ] = useState(""); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const load = useCallback(async () => { setLoading(true); try { const response = await fetch(`${baseUrl}/api/mobile/v1/feed?limit=40`); if (!response.ok) throw new Error(); const data = await response.json(); setItems(data.items); setError(""); } catch { setError("Artworks could not be loaded. The Shopify cache may still need its first sync."); } finally { setLoading(false); } }, [baseUrl]); useFocusEffect(useCallback(() => { void load(); void track(api, "explore_view"); }, [load, api])); const shown = q ? items.filter((item) => `${item.title} ${item.artistName} ${item.tags.join(" ")}`.toLowerCase().includes(q.toLowerCase())) : items; return <Page title="Explore art" subtitle="A visual catalog sourced from Shopify." refreshControl={<RefreshControl refreshing={loading} onRefresh={() => void load()} tintColor={colors.text}/>}><Field label="Search artworks" value={q} onChangeText={setQ} placeholder="Artist, title or tag"/>{error ? <ErrorState message={error} retry={load}/> : shown.length ? <View style={{ flexDirection: "row", flexWrap: "wrap", gap: 8 }}>{shown.map((item) => <Pressable key={item.id} onPress={() => { void track(api, "explore_artwork_click", { artworkId: item.id }); router.push(`/artwork/${encodeURIComponent(item.handle || item.id)}` as never); }} style={{ width: "48.7%", gap: 5, marginBottom: 9 }}><Image source={item.images[0]?.urlMedium} style={{ width: "100%", aspectRatio: item.images[0]?.aspectRatio || 4 / 5, borderRadius: 4, backgroundColor: colors.surfaceMuted }} contentFit="cover"/><Text style={{ color: colors.text, fontWeight: "600" }} numberOfLines={1}>{item.title || "Untitled"}</Text><Text style={{ color: colors.textMuted, fontSize: 12 }} numberOfLines={1}>{item.artistName}</Text></Pressable>)}</View> : <Empty text={loading ? "Loading artworks…" : "No artworks match this search."}/>}</Page>; }
