import Constants from "expo-constants";
import * as Device from "expo-device";
import * as Notifications from "expo-notifications";
import * as SecureStore from "expo-secure-store";
import { useRouter } from "expo-router";
import { useState } from "react";
import { Alert, Linking, Platform, Pressable, Text, View } from "react-native";
import { useAuth } from "../src/auth";
import { type ThemePreference, useTheme } from "../src/theme";
import { Button, Page, Section } from "../src/ui";
const DEVICE_KEY = "artclub:device-id";
const preferences: ThemePreference[] = ["light", "dark", "system"];
async function deviceId() { const stored = await SecureStore.getItemAsync(DEVICE_KEY); if (stored) return stored; const next = `device-${Date.now()}-${Math.random().toString(36).slice(2)}`; await SecureStore.setItemAsync(DEVICE_KEY, next); return next; }
export default function Settings() { const { api, logout } = useAuth(); const { colors, preference, setPreference } = useTheme(); const router = useRouter(); const [push, setPush] = useState("Not configured"); const [busy, setBusy] = useState(false); async function registerPush() { setBusy(true); try { if (!Device.isDevice) throw new Error("Push notifications require an iOS or Android development build on a physical device."); if (Platform.OS === "android") await Notifications.setNotificationChannelAsync("default", { name: "ARTCLUB", importance: Notifications.AndroidImportance.DEFAULT }); let permission = await Notifications.getPermissionsAsync(); if (!permission.granted) permission = await Notifications.requestPermissionsAsync(); if (!permission.granted) throw new Error("Notification permission was not granted."); const projectId = Constants.expoConfig?.extra?.eas?.projectId || Constants.easConfig?.projectId; if (!projectId) throw new Error("The EAS project ID is missing."); const token = await Notifications.getExpoPushTokenAsync({ projectId }); await api.request("/push-token", { method: "POST", body: JSON.stringify({ token: token.data, deviceId: await deviceId(), platform: Platform.OS }) }); setPush("Enabled on this device"); } catch (reason) { setPush(reason instanceof Error ? reason.message : "Push setup failed."); } finally { setBusy(false); } } return <Page title="Settings" subtitle="Appearance, notifications and account."><Section title="Appearance"><View style={{ flexDirection: "row", gap: 8 }}>{preferences.map((item) => <Pressable key={item} onPress={() => setPreference(item)} style={{ flex: 1, minHeight: 44, borderRadius: 6, borderWidth: 1, borderColor: preference === item ? colors.text : colors.border, alignItems: "center", justifyContent: "center", backgroundColor: preference === item ? colors.surfaceMuted : colors.surface }}><Text style={{ color: colors.text, textTransform: "capitalize", fontWeight: preference === item ? "600" : "400" }}>{item}</Text></Pressable>)}</View></Section><Section title="Push notifications"><Text style={{ color: colors.textMuted, lineHeight: 20 }}>{push}</Text><Button label={busy ? "Registering…" : "Enable push notifications"} variant="secondary" icon="notifications-outline" onPress={() => void registerPush()} disabled={busy}/></Section><Section title="Links"><Button label="Privacy and account settings" variant="secondary" onPress={() => void Linking.openURL("https://network.artclub.wtf/settings")}/></Section><Section title="Account"><Button label="Log out" variant="secondary" onPress={() => Alert.alert("Log out?", "Your secure session will be removed from this device.", [{ text: "Cancel" }, { text: "Log out", style: "destructive", onPress: () => void logout().then(() => router.replace("/login")) }])}/></Section></Page>; }
