import { Image } from "expo-image";
import { useFocusEffect } from "expo-router";
import { useCallback, useState } from "react";
import { RefreshControl, Text, View } from "react-native";
import { track } from "../src/analytics";
import { useAuth } from "../src/auth";
import { useTheme } from "../src/theme";
import { Avatar, Empty, ErrorState, Page, Row, Section } from "../src/ui";
export default function Updates() { const { api } = useAuth(); const { colors } = useTheme(); const [items, setItems] = useState<any[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const load = useCallback(async () => { setLoading(true); try { const data = await api.request("/updates"); setItems(data.items); setError(""); } catch { setError("Updates could not be loaded."); } finally { setLoading(false); } }, [api]); useFocusEffect(useCallback(() => { void load(); void track(api, "updates_view"); }, [load, api])); return <Page title="Updates" subtitle="Chronological news from connections and profiles you follow." refreshControl={<RefreshControl refreshing={loading} onRefresh={() => void load()} tintColor={colors.text}/>} >{error ? <ErrorState message={error} retry={load}/> : items.length ? items.map((item) => <Section key={item.id} title=""><Row><Avatar profile={item.author}/><View style={{ flex: 1 }}><Text style={{ color: colors.text, fontWeight: "600" }}>{item.author?.displayName}</Text><Text style={{ color: colors.textMuted, fontSize: 11 }}>{new Date(item.createdAt).toLocaleString()}</Text></View></Row>{item.text ? <Text style={{ color: colors.text, lineHeight: 21 }}>{item.text}</Text> : null}{item.media?.[0]?.url ? <Image source={item.media[0].url} style={{ width: "100%", aspectRatio: 4 / 5, borderRadius: 4, backgroundColor: colors.surfaceMuted }} contentFit="cover"/> : null}<Text style={{ color: colors.textMuted, fontSize: 12 }}>{item.likeCount} likes · {item.commentCount} comments</Text></Section>) : <Empty text={loading ? "Loading updates…" : "No updates yet. Follow profiles or make connections to build this space."}/>}</Page>; }
