import Ionicons from "@expo/vector-icons/Ionicons";
import { Image } from "expo-image";
import { useRouter } from "expo-router";
import React from "react";
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, TextInput, View, type TextInputProps } from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";

import { useTheme } from "./theme";

export function Page({ children, title, subtitle, refreshControl }: { children: React.ReactNode; title?: string; subtitle?: string; refreshControl?: React.ReactElement }) { const { colors } = useTheme(); return <ScrollView refreshControl={refreshControl as any} keyboardShouldPersistTaps="handled" contentContainerStyle={[styles.page, { backgroundColor: colors.background }]}>{title ? <Text style={[styles.title, { color: colors.text }]}>{title}</Text> : null}{subtitle ? <Text style={[styles.subtitle, { color: colors.textMuted }]}>{subtitle}</Text> : null}{children}</ScrollView>; }
export function Section({ title, action, children }: { title: string; action?: React.ReactNode; children: React.ReactNode }) { const { colors } = useTheme(); return <View style={[styles.section, { borderColor: colors.border, backgroundColor: colors.surface }]}><View style={styles.sectionHeader}><Text style={[styles.sectionTitle, { color: colors.text }]}>{title}</Text>{action}</View>{children}</View>; }
export function Button({ label, onPress, variant = "primary", disabled = false, icon }: { label: string; onPress: () => void; variant?: "primary" | "secondary" | "text"; disabled?: boolean; icon?: keyof typeof Ionicons.glyphMap }) { const { colors } = useTheme(); const bg = variant === "primary" ? colors.text : variant === "secondary" ? colors.surfaceMuted : "transparent"; const fg = variant === "primary" ? colors.background : variant === "secondary" ? colors.text : colors.textMuted; return <Pressable accessibilityRole="button" accessibilityLabel={label} disabled={disabled} onPress={onPress} style={[styles.button, { backgroundColor: bg, opacity: disabled ? .45 : 1 }]}>{icon ? <Ionicons name={icon} size={17} color={fg}/> : null}<Text style={[styles.buttonText, { color: fg }]}>{label}</Text></Pressable>; }
export function Field({ label, multiline, ...props }: TextInputProps & { label: string }) { const { colors } = useTheme(); return <View style={styles.field}><Text style={[styles.label, { color: colors.text }]}>{label}</Text><TextInput {...props} multiline={multiline} placeholderTextColor={colors.textMuted} style={[styles.input, multiline && styles.multiline, { color: colors.text, borderColor: colors.border, backgroundColor: colors.surface }]}/></View>; }
export function Avatar({ profile, size = 44 }: { profile: any; size?: number }) { const { colors } = useTheme(); return profile?.profileImageUrl ? <Image source={profile.profileImageUrl} style={{ width: size, height: size, borderRadius: size / 2 }} contentFit="cover"/> : <View style={[styles.avatar, { width: size, height: size, borderRadius: size / 2, backgroundColor: colors.surfaceMuted }]}><Text style={{ color: colors.text, fontWeight: "600" }}>{profile?.displayName?.[0] || "A"}</Text></View>; }
export function Row({ children, onPress }: { children: React.ReactNode; onPress?: () => void }) { const { colors } = useTheme(); const content = <View style={[styles.row, { borderBottomColor: colors.border }]}>{children}</View>; return onPress ? <Pressable onPress={onPress}>{content}</Pressable> : content; }
export function Empty({ text, action, onAction }: { text: string; action?: string; onAction?: () => void }) { const { colors } = useTheme(); return <View style={styles.empty}><Text style={[styles.emptyText, { color: colors.textMuted }]}>{text}</Text>{action && onAction ? <Button label={action} onPress={onAction} variant="secondary"/> : null}</View>; }
export function Loading() { const { colors } = useTheme(); return <View style={[styles.center, { backgroundColor: colors.background }]}><ActivityIndicator color={colors.text}/></View>; }
export function ErrorState({ message, retry }: { message: string; retry?: () => void }) { const { colors } = useTheme(); return <View style={styles.empty}><Text style={{ color: colors.danger }}>{message}</Text>{retry ? <Button label="Try again" onPress={retry} variant="secondary"/> : null}</View>; }
export function GlobalHeader({ unread = 0 }: { unread?: number }) { const { colors } = useTheme(); const router = useRouter(); const insets = useSafeAreaInsets(); return <View style={[styles.header, { paddingTop: insets.top, height: insets.top + 54, borderBottomColor: colors.border, backgroundColor: colors.background }]}><Pressable accessibilityLabel="Create" onPress={() => router.push("/create")} style={styles.headerAction}><Ionicons name="add" size={24} color={colors.text}/></Pressable><Text style={[styles.wordmark, { color: colors.text }]}>ARTCLUB</Text><Pressable accessibilityLabel="Notifications" onPress={() => router.push("/notifications")} style={styles.headerAction}><Ionicons name="notifications-outline" size={21} color={colors.text}/>{unread > 0 ? <View style={[styles.badge, { backgroundColor: colors.danger }]}><Text style={[styles.badgeText, { color: colors.background }]}>{unread > 9 ? "9+" : unread}</Text></View> : null}</Pressable></View>; }
export function TextLink({ label, onPress }: { label: string; onPress: () => void }) { const { colors } = useTheme(); return <Pressable onPress={onPress}><Text style={{ color: colors.textMuted, fontSize: 13 }}>{label}</Text></Pressable>; }

export const styles = StyleSheet.create({ page: { flexGrow: 1, padding: 12, paddingBottom: 36, gap: 12 }, title: { fontSize: 30, lineHeight: 34, fontWeight: "600", letterSpacing: -1 }, subtitle: { fontSize: 14, lineHeight: 21, marginTop: -6, marginBottom: 6 }, section: { borderWidth: StyleSheet.hairlineWidth, borderRadius: 4, padding: 14, gap: 10 }, sectionHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 12 }, sectionTitle: { fontSize: 18, fontWeight: "600" }, button: { minHeight: 44, borderRadius: 6, paddingHorizontal: 15, flexDirection: "row", gap: 7, alignItems: "center", justifyContent: "center" }, buttonText: { fontSize: 14, fontWeight: "600" }, field: { gap: 6 }, label: { fontSize: 13, fontWeight: "500" }, input: { minHeight: 46, borderWidth: StyleSheet.hairlineWidth, borderRadius: 6, paddingHorizontal: 12, fontSize: 15 }, multiline: { minHeight: 110, paddingTop: 12, textAlignVertical: "top" }, avatar: { alignItems: "center", justifyContent: "center" }, row: { minHeight: 62, flexDirection: "row", alignItems: "center", gap: 12, borderBottomWidth: StyleSheet.hairlineWidth, paddingVertical: 10 }, empty: { alignItems: "center", gap: 14, paddingVertical: 22, paddingHorizontal: 12 }, emptyText: { textAlign: "center", fontSize: 14, lineHeight: 21 }, center: { flex: 1, alignItems: "center", justifyContent: "center" }, header: { borderBottomWidth: StyleSheet.hairlineWidth, flexDirection: "row", alignItems: "flex-end", justifyContent: "space-between", paddingHorizontal: 8, paddingBottom: 7 }, headerAction: { width: 40, height: 40, alignItems: "center", justifyContent: "center" }, wordmark: { fontSize: 13, fontWeight: "700", letterSpacing: 1.6, height: 40, textAlignVertical: "center", paddingTop: 11 }, badge: { position: "absolute", right: 2, top: 2, minWidth: 16, height: 16, borderRadius: 8, alignItems: "center", justifyContent: "center", paddingHorizontal: 3 }, badgeText: { fontSize: 9, fontWeight: "700" } });
