"use client";
import { createNetworkApiClient } from "@artclub/api-client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { PublicArtistProfilePage } from "@/components/public-profile/PublicArtistProfilePage";
import { trackNetwork } from "@/lib/client/network-analytics";
import type { PublicArtistProfilePageData } from "@/lib/types";
const api = createNetworkApiClient();
type Props = { profile: any; artistProfile?: PublicArtistProfilePageData | null; viewerMode: "public" | "network"; mine?: boolean };

export function UnifiedProfileView({ profile, artistProfile, viewerMode, mine = false }: Props) {
  const [details, setDetails] = useState<any>(null); const [error, setError] = useState("");
  useEffect(() => { if (viewerMode !== "network") return; api.request<any>(`/profiles/${encodeURIComponent(profile.slug)}`).then(setDetails).catch((e: any) => setError(e.message)); trackNetwork("profile_view", { targetProfileId: profile.networkProfileId }); }, [profile.slug, profile.networkProfileId, viewerMode]);
  const state = details?.relation?.state || "none"; const followed = details?.viewer?.followed === true; const liked = details?.viewer?.liked === true;
  const counts = details?.counts || { connections: 0, followers: 0, following: 0, likes: 0, posts: 0, events: 0, artworks: 0 };
  async function connection(action?: string) { try { if (!action) { const data = await api.request<any>("/connections", { method: "POST", body: JSON.stringify({ profileId: profile.id }) }); setDetails((value: any) => ({ ...value, relation: data.connection })); return; } const data = await api.request<any>(`/connections/${details.relation.id}`, { method: "PATCH", body: JSON.stringify({ action }) }); if (action === "accept") trackNetwork("connection_request_accepted", { targetProfileId: profile.networkProfileId }); if (action === "decline") trackNetwork("connection_request_declined", { targetProfileId: profile.networkProfileId }); setDetails((value: any) => ({ ...value, relation: data.connection, counts: { ...value.counts, connections: value.counts.connections + (action === "accept" ? 1 : action === "remove" ? -1 : 0) } })); } catch (e: any) { setError(e.message); } }
  async function follow() { try { await api.request(`/profiles/${encodeURIComponent(profile.id)}/follow`, { method: followed ? "DELETE" : "POST" }); trackNetwork(followed ? "profile_unfollow" : "profile_follow", { targetProfileId: profile.networkProfileId }); setDetails((value: any) => ({ ...value, viewer: { ...value.viewer, followed: !followed }, counts: { ...value.counts, followers: value.counts.followers + (followed ? -1 : 1) } })); } catch (e: any) { setError(e.message); } }
  async function appreciate() { try { await api.request(`/profiles/${encodeURIComponent(profile.id)}/like`, { method: liked ? "DELETE" : "POST" }); trackNetwork(liked ? "profile_unlike" : "profile_like", { targetProfileId: profile.networkProfileId }); setDetails((value: any) => ({ ...value, viewer: { ...value.viewer, liked: !liked }, counts: { ...value.counts, likes: value.counts.likes + (liked ? -1 : 1) } })); } catch (e: any) { setError(e.message); } }
  async function message() { try { if (state === "connected") { const data = await api.request<any>("/conversations", { method: "POST", body: JSON.stringify({ profileId: profile.id }) }); location.href = `/messages/${data.conversation.id}`; return; } const text = prompt("Message request (max. 100 characters)"); if (!text) return; await api.request("/message-requests", { method: "POST", body: JSON.stringify({ profileId: profile.id, text: text.slice(0, 100) }) }); trackNetwork("message_request_sent", { targetProfileId: profile.networkProfileId }); setDetails((value: any) => ({ ...value, relation: { ...value.relation, state: "outgoing_pending" } })); } catch (e: any) { setError(e.message); } }
  async function share(native = false) { const url = profile.profileType === "artist" ? `${location.origin}/artist/${profile.slug}` : `${location.origin}/profile/${profile.slug}`; if (native && navigator.share) { await navigator.share({ title: profile.displayName, url }); trackNetwork("profile_native_share", { targetProfileId: profile.networkProfileId }); } else { await navigator.clipboard.writeText(url); trackNetwork("profile_link_copy", { targetProfileId: profile.networkProfileId }); } trackNetwork("profile_share", { targetProfileId: profile.networkProfileId }); }
  function ForeignActions() { if (state === "blocked") return <span className="text-sm text-neutral-500">Interactions unavailable</span>; return <>{state === "none" && <button onClick={() => void connection()} className="rounded-full bg-neutral-950 px-4 py-2 text-sm text-white dark:bg-white dark:text-black">Connect</button>}{state === "outgoing_pending" && <><span className="text-sm">Request sent</span><button onClick={() => void connection("cancel")} className="text-sm underline">Cancel request</button></>}{state === "incoming_pending" && <><button onClick={() => void connection("accept")} className="rounded-full bg-neutral-950 px-4 py-2 text-sm text-white dark:bg-white dark:text-black">Accept</button><button onClick={() => void connection("decline")} className="rounded-full border px-4 py-2 text-sm">Decline</button></>}{state === "connected" && <><button onClick={() => void message()} className="rounded-full bg-neutral-950 px-4 py-2 text-sm text-white dark:bg-white dark:text-black">Message</button><span className="text-sm">Connected</span><button onClick={() => void connection("remove")} className="text-sm underline">Remove</button></>}{state !== "connected" && <button onClick={() => void message()} className="rounded-full border px-4 py-2 text-sm">Message request</button>}<button onClick={() => void follow()} className="rounded-full border px-4 py-2 text-sm">{followed ? "Unfollow" : "Follow"}</button><button onClick={() => void appreciate()} className="rounded-full border px-4 py-2 text-sm">{liked ? "Appreciated" : "Appreciate"}</button><button onClick={() => void share(true)} className="text-sm underline">Share</button></>; }
  const actions = viewerMode === "network" ? <div className="mx-auto max-w-6xl px-4 pt-4"><div className="flex flex-wrap items-center gap-2 rounded-2xl border bg-white/95 p-3 dark:border-neutral-800 dark:bg-neutral-950">{mine ? <><Link href="/settings/profile" className="rounded-full bg-neutral-950 px-4 py-2 text-sm text-white dark:bg-white dark:text-black">Edit profile</Link><Link href="/create" className="rounded-full border px-4 py-2 text-sm">Create</Link><Link href="/analytics" className="rounded-full border px-4 py-2 text-sm">Analytics</Link><button onClick={() => void share(true)} className="rounded-full border px-4 py-2 text-sm">Share profile</button><button onClick={() => void share(false)} className="text-sm underline">Copy link</button><span className="text-sm text-neutral-500">Your ARTCLUB profile is your identity in the art world.</span></> : <ForeignActions />}</div>{error && <p className="mt-2 text-sm text-red-600">{error}</p>}<div className="flex gap-5 px-2 py-3 text-sm text-neutral-500"><span>{counts.connections} connections</span><span>{counts.followers} followers</span><span>{counts.likes} appreciations</span></div>{mine && counts.posts === 0 && <div className="flex flex-wrap gap-3 pb-3 text-sm"><Link href="/create">Share an update →</Link>{profile.profileType === "artist" && <Link href="/artworks/new">Add your first artwork →</Link>}<Link href="/events/new">Add an event →</Link></div>}</div> : null;
  if (artistProfile) return <>{actions}<PublicArtistProfilePage profile={artistProfile} /></>;
  return <>{actions}<main className="mx-auto max-w-4xl pb-16"><div className="h-52 overflow-hidden rounded-b-3xl bg-neutral-100 dark:bg-neutral-800">{profile.coverImageUrl && <img src={profile.coverImageUrl} alt="" className="h-full w-full object-cover" />}</div><div className="px-5"><div className="-mt-12">{profile.profileImageUrl ? <img src={profile.profileImageUrl} alt="" className="h-24 w-24 rounded-full border-4 border-white object-cover dark:border-neutral-950" /> : <div className="grid h-24 w-24 place-items-center rounded-full bg-neutral-900 text-3xl text-white">{profile.displayName[0]}</div>}</div><h1 className="mt-4 text-4xl font-semibold">{profile.displayName}</h1><p className="text-neutral-500">@{profile.username} · {profile.profileType.replaceAll("_", " ")}</p><p className="mt-6 max-w-2xl whitespace-pre-wrap leading-7">{profile.bio}</p><nav className="mt-10 flex gap-6 border-b pb-3 text-sm"><span>Posts</span>{["collector", "art_enthusiast"].includes(profile.profileType) && <Link href="/collection">Collection</Link>}<span>Events</span><span>About</span><span>Connections</span></nav></div></main></>;
}
