import { useRouter } from "expo-router";
import { useState } from "react";
import { Text } from "react-native";
import { track } from "../../src/analytics";
import { useAuth } from "../../src/auth";
import { pickImages, uploadAsset } from "../../src/media";
import { useTheme } from "../../src/theme";
import { Button, Field, Page } from "../../src/ui";
export default function CreateEvent() { const { api } = useAuth(); const { colors } = useTheme(); const router = useRouter(); const [title, setTitle] = useState(""); const [description, setDescription] = useState(""); const [startAt, setStartAt] = useState(new Date(Date.now() + 86_400_000).toISOString().slice(0, 16)); const [endAt, setEndAt] = useState(""); const [venueName, setVenueName] = useState(""); const [address, setAddress] = useState(""); const [city, setCity] = useState(""); const [ticketUrl, setTicketUrl] = useState(""); const [cover, setCover] = useState<any>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); async function submit() { setBusy(true); setError(""); try { const media = cover ? await uploadAsset(api, cover) : null; const payload = { title, description, startAt: new Date(startAt).toISOString(), ...(endAt ? { endAt: new Date(endAt).toISOString() } : {}), timezone: Intl.DateTimeFormat().resolvedOptions().timeZone, venueName, address, city, country: "", isOnline: false, ticketUrl, coverImageUrl: media?.url || "", coverImageStorageKey: media?.storageKey, rsvpEnabled: true, visibility: "public", participantProfileIds: [], status: "published" }; const data = await api.request("/events", { method: "POST", body: JSON.stringify(payload) }); void track(api, "event_published", { eventId: data.event.id }); router.replace(`/events/${data.event.id}` as never); } catch (reason) { setError(reason instanceof Error ? reason.message.replaceAll("_", " ") : "The event could not be created."); } finally { setBusy(false); } } return <Page title="Create event" subtitle="Use local date and time in YYYY-MM-DDTHH:mm format."><Field label="Title" value={title} onChangeText={setTitle}/><Field label="Description" value={description} onChangeText={setDescription} multiline/><Field label="Starts" value={startAt} onChangeText={setStartAt} autoCapitalize="none"/><Field label="Ends (optional)" value={endAt} onChangeText={setEndAt} autoCapitalize="none"/><Field label="Venue" value={venueName} onChangeText={setVenueName}/><Field label="Address" value={address} onChangeText={setAddress}/><Field label="City" value={city} onChangeText={setCity}/><Field label="Ticket URL (optional)" value={ticketUrl} onChangeText={setTicketUrl} autoCapitalize="none" keyboardType="url"/><Button label={cover ? "Cover selected" : "Choose cover"} variant="secondary" icon="image-outline" onPress={() => void pickImages().then((items) => setCover(items[0] || null)).catch((reason) => setError(reason.message))}/>{error ? <Text style={{ color: colors.danger, textTransform: "capitalize" }}>{error}</Text> : null}<Button label={busy ? "Publishing…" : "Publish event"} onPress={() => void submit()} disabled={busy || !title || !startAt || (!venueName && !address)}/></Page>; }
