import { Image } from "expo-image";
import { usePathname, useRouter } from "expo-router";
import { useState } from "react";
import { Text, View } from "react-native";
import { track } from "../../src/analytics";
import { useAuth } from "../../src/auth";
import { pickMedia, uploadAsset } from "../../src/media";
import { useTheme } from "../../src/theme";
import { Button, Field, Page } from "../../src/ui";
export default function CreateUpdate() { const { api } = useAuth(); const { colors } = useTheme(); const router = useRouter(); const pathname = usePathname(); const processMode = pathname.endsWith("/process"); const [text, setText] = useState(""); const [assets, setAssets] = useState<any[]>([]); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); async function select() { try { setAssets(await pickMedia(true)); } catch (reason) { setError(reason instanceof Error ? reason.message : "Media could not be selected."); } } async function submit() { setBusy(true); setError(""); try { const media = await Promise.all(assets.map((asset) => uploadAsset(api, asset))); const type = processMode ? "process" : media.some((item) => item.type === "video") ? "video" : media.length ? "image" : "text"; await api.request("/updates", { method: "POST", body: JSON.stringify({ type, text, media, visibility: "public" }) }); void track(api, "post_create"); router.replace("/updates"); } catch (reason) { setError(reason instanceof Error ? reason.message.replaceAll("_", " ") : "The update could not be published."); } finally { setBusy(false); } } return <Page title={processMode ? "Share process" : "Post update"} subtitle="Updates are chronological and visible to your network."><Field label={processMode ? "Process note" : "Update"} value={text} onChangeText={setText} multiline placeholder={processMode ? "What are you working on?" : "What should your network know?"}/><Button label={assets.length ? "Change media" : "Add images or video"} variant="secondary" icon="images-outline" onPress={() => void select()}/>{assets.length ? <View style={{ flexDirection: "row", flexWrap: "wrap", gap: 6 }}>{assets.map((asset) => asset.type === "video" ? <View key={asset.uri} style={{ width: "31.5%", aspectRatio: 1, borderRadius: 4, backgroundColor: colors.surfaceMuted, alignItems: "center", justifyContent: "center" }}><Text style={{ color: colors.textMuted, fontSize: 12 }}>Video</Text></View> : <Image key={asset.uri} source={asset.uri} style={{ width: "31.5%", aspectRatio: 1, borderRadius: 4, backgroundColor: colors.surfaceMuted }}/>)}</View> : null}{busy && assets.length ? <Text style={{ color: colors.textMuted }}>Uploading {assets.length} media file{assets.length === 1 ? "" : "s"}…</Text> : null}{error ? <Text style={{ color: colors.danger }}>{error}</Text> : null}<Button label={busy ? "Publishing…" : processMode ? "Publish process" : "Publish update"} onPress={() => void submit()} disabled={busy || (!text.trim() && !assets.length)}/></Page>; }
