"use client";
import {createNetworkApiClient} from "@artclub/api-client";
import Link from "next/link";
import {useEffect,useRef,useState} from "react";
import {ActionIcon} from "@/components/icons/ActionIcon";
import {trackNetwork} from "@/lib/client/network-analytics";
const api=createNetworkApiClient();

export function EventFeedCard({initial}:{initial:any}){
  const[event,setEvent]=useState(initial);const[error,setError]=useState("");const[busy,setBusy]=useState(false);const root=useRef<HTMLElement>(null);
  useEffect(()=>{const element=root.current;if(!element)return;const observer=new IntersectionObserver(([entry])=>{if(entry.isIntersecting){trackNetwork("event_impression",{eventId:event.id});observer.disconnect()}},{threshold:.5});observer.observe(element);return()=>observer.disconnect()},[event.id]);
  async function toggle(kind:"rsvp"|"save"){if(busy)return;const key=kind==="rsvp"?"attending":"saved";const active=event[key];const previous=event;setBusy(true);setError("");setEvent((value:any)=>({...value,[key]:!active,...(kind==="rsvp"?{rsvpCount:Math.max(0,value.rsvpCount+(active?-1:1))}:{})}));try{const data=await api.request<any>(`/events/${event.id}/${kind}`,{method:active?"DELETE":"POST"});setEvent((value:any)=>({...value,...data}));trackNetwork(kind==="save"?"event_save":active?"event_rsvp_removed":"event_rsvp",{eventId:event.id})}catch(reason:any){setEvent(previous);setError(reason.message)}finally{setBusy(false)}}
  async function share(){const url=`${location.origin}/events/${event.id}`;if(navigator.share)await navigator.share({title:event.title,url});else await navigator.clipboard.writeText(url);trackNetwork("event_share",{eventId:event.id})}
  const place=event.isOnline?"Online":[event.venueName,event.city].filter(Boolean).join(" · ");
  return <article ref={root} className="overflow-hidden rounded-2xl bg-[var(--surface-muted)] text-[var(--text)]">{event.coverImageUrl?<Link href={`/events/${event.id}`} onClick={()=>trackNetwork("event_view",{eventId:event.id})}><img src={event.coverImageUrl} alt={event.title} loading="lazy" decoding="async" sizes="(max-width: 767px) 100vw, 700px" className="aspect-[4/5] w-full object-cover"/></Link>:<div className="aspect-[4/5] bg-[var(--surface-muted)]"/>}<div className="p-4"><div className="flex items-center justify-between"><span className="eyebrow">Event</span>{event.status==="cancelled"?<span className="rounded-full bg-[var(--danger)] px-3 py-1 text-xs text-[var(--danger-foreground)]">Cancelled</span>:null}</div><p className="meta-text mt-3">{new Intl.DateTimeFormat(undefined,{dateStyle:"full",timeStyle:"short",timeZone:event.timezone}).format(new Date(event.startAt))}</p><Link href={`/events/${event.id}`} className="mt-1 block text-2xl font-semibold leading-tight">{event.title}</Link><p className="meta-text mt-1">{place}</p>{event.organizer?<p className="mt-3 text-sm">By <Link className="font-medium" href={`/profile/${event.organizer.slug}`}>{event.organizer.displayName}</Link></p>:null}<div className="mt-4 flex items-center gap-2"><button disabled={busy||!["available","attending"].includes(event.rsvpState)} onClick={()=>void toggle("rsvp")} className="primary-action disabled:opacity-40">{event.attending?"Going":event.rsvpState==="full"?"Full":"RSVP"}</button><span className="meta-text">{event.rsvpCount} going</span><button disabled={busy} onClick={()=>void toggle("save")} aria-label={event.saved?"Remove saved event":"Save event"} title={event.saved?"Unsave":"Save"} className="ml-auto grid h-10 w-10 place-items-center"><ActionIcon name="save" filled={event.saved}/></button><button onClick={()=>void share()} aria-label="Share event" title="Share" className="grid h-10 w-10 place-items-center"><ActionIcon name="share"/></button>{event.ticketUrl?<a href={event.ticketUrl} target="_blank" rel="noreferrer" onClick={()=>trackNetwork("event_ticket_click",{eventId:event.id})} className="text-sm font-medium">Tickets</a>:null}</div>{error?<p className="mt-3 text-sm text-[var(--danger)]">{error}</p>:null}</div></article>;
}
