"use client";

import type { ExploreArtwork } from "@artclub/models";
import { createNetworkApiClient } from "@artclub/api-client";
import Link from "next/link";
import { FormEvent, useCallback, useEffect, useRef, useState } from "react";

import { trackNetwork } from "@/lib/client/network-analytics";

const api=createNetworkApiClient();

function ArtworkCard({artwork,onPatch}:{artwork:ExploreArtwork;onPatch:(patch:Partial<ExploreArtwork>)=>void}){
  const ref=useRef<HTMLElement>(null);const impressed=useRef(false);
  useEffect(()=>{const node=ref.current;if(!node)return;const observer=new IntersectionObserver(entries=>{if(entries[0]?.isIntersecting&&entries[0].intersectionRatio>=.5&&!impressed.current){impressed.current=true;trackNetwork("explore_artwork_impression",{canonicalProductId:artwork.id})}},{threshold:.5});observer.observe(node);return()=>observer.disconnect()},[artwork.id]);
  async function action(kind:"like"|"save"){const active=kind==="like"?artwork.liked:artwork.saved;onPatch({[kind==="like"?"liked":"saved"]:!active,...(kind==="like"?{likeCount:Math.max(0,artwork.likeCount+(active?-1:1))}:{})});try{await api.request(`/artworks/${artwork.id}/${kind}`,{method:active?"DELETE":"POST"});trackNetwork(kind==="like"?"explore_artwork_like":"explore_artwork_save",{canonicalProductId:artwork.id})}catch{onPatch({[kind==="like"?"liked":"saved"]:active,...(kind==="like"?{likeCount:artwork.likeCount}:{})})}}
  async function share(){await navigator.share?.({title:artwork.title,url:`${location.origin}/explore-art/${artwork.id}`});trackNetwork("explore_artwork_share",{canonicalProductId:artwork.id})}
  return <article ref={ref} className="group relative mb-3 break-inside-avoid overflow-hidden rounded-xl bg-[var(--surface-soft)]"><Link href={`/explore-art/${artwork.id}`} onClick={()=>trackNetwork("explore_artwork_click",{canonicalProductId:artwork.id})} className="block"><img src={artwork.imageUrl} alt={artwork.title} loading="lazy" decoding="async" width={artwork.width||undefined} height={artwork.height||undefined} style={artwork.width&&artwork.height?{aspectRatio:`${artwork.width}/${artwork.height}`}:{}} className="h-auto w-full object-cover"/></Link><div className="pointer-events-none absolute inset-x-0 bottom-0 bg-gradient-to-t from-black/75 via-black/20 to-transparent p-3 pt-12 text-white opacity-0 transition-opacity group-hover:opacity-100 group-focus-within:opacity-100"><Link href={`/explore-art/${artwork.id}`} className="pointer-events-auto block text-sm font-medium">{artwork.title}</Link><Link href={`/profile/${artwork.artist.slug}`} onClick={()=>trackNetwork("explore_artist_click",{canonicalProductId:artwork.id})} className="pointer-events-auto text-xs text-white/80">{artwork.artist.displayName}</Link><div className="pointer-events-auto mt-2 flex gap-3 text-xs"><button onClick={()=>void action("like")}>{artwork.liked?"Appreciated":"Appreciate"}</button><button onClick={()=>void action("save")}>{artwork.saved?"Saved":"Save"}</button><button onClick={()=>void share()}>Share</button>{artwork.shopUrl?<a href={artwork.shopUrl} target="_blank" rel="noreferrer" onClick={()=>trackNetwork("explore_shop_click",{canonicalProductId:artwork.id})}>Shop</a>:null}</div></div></article>
}

export function ExploreArtClient(){
  const[items,setItems]=useState<ExploreArtwork[]>([]);const[next,setNext]=useState<string|null>(null);const[facets,setFacets]=useState<string[]>([]);const[category,setCategory]=useState("All");const[sort,setSort]=useState<"recent"|"popular">("recent");const[query,setQuery]=useState("");const[submittedQuery,setSubmittedQuery]=useState("");const[loading,setLoading]=useState(false);const[error,setError]=useState("");const sentinel=useRef<HTMLDivElement>(null);
  const load=useCallback(async(cursor?:string)=>{setLoading(true);setError("");try{const data=await api.exploreArt({cursor,q:submittedQuery||undefined,category:category==="All"?undefined:category,sort});setItems(current=>cursor?[...current,...data.items.filter(item=>!current.some(existing=>existing.id===item.id))]:data.items);setNext(data.nextCursor);setFacets(data.facets)}catch{setError("Explore Art could not be loaded.")}finally{setLoading(false)}},[category,sort,submittedQuery]);
  useEffect(()=>{void load();trackNetwork("explore_view")},[load]);
  useEffect(()=>{const node=sentinel.current;if(!node)return;const observer=new IntersectionObserver(entries=>{if(entries[0]?.isIntersecting&&next&&!loading)void load(next)},{rootMargin:"600px"});observer.observe(node);return()=>observer.disconnect()},[load,loading,next]);
  function search(event:FormEvent){event.preventDefault();setSubmittedQuery(query.trim())}
  function choose(value:string){setCategory(value);trackNetwork("explore_filter_changed",{filter:value})}
  return <main className="app-page max-w-none"><header className="mb-7 flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><h1 className="page-heading">Explore Art</h1><p className="meta-text mt-2">Discover published work from artists across ARTCLUB.</p></div><form onSubmit={search} className="flex gap-2"><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search artworks" className="control min-w-0 flex-1 lg:w-72"/><button className="secondary-action">Search</button></form></header><div className="mb-6 flex flex-wrap items-center justify-between gap-3"><div className="flex flex-wrap gap-2">{["All",...facets].map(value=><button key={value} onClick={()=>choose(value)} className={category===value?"primary-action !min-h-9 !px-3":"secondary-action !min-h-9 !px-3"}>{value}</button>)}</div><select value={sort} onChange={event=>{setSort(event.target.value as "recent"|"popular");trackNetwork("explore_filter_changed",{sort:event.target.value})}} className="control min-h-9 py-1"><option value="recent">Recent</option><option value="popular">Popular</option></select></div>{!items.length&&loading?<div className="columns-2 gap-3 md:columns-3 xl:columns-4 2xl:columns-5">{Array.from({length:12},(_,index)=><div key={index} className={`mb-3 animate-pulse break-inside-avoid rounded-xl bg-[var(--surface-soft)] ${index%3===0?"h-72":"h-52"}`}/>)}</div>:<div className="columns-2 gap-3 md:columns-3 xl:columns-4 2xl:columns-5">{items.map(artwork=><ArtworkCard key={artwork.id} artwork={artwork} onPatch={patch=>setItems(current=>current.map(item=>item.id===artwork.id?{...item,...patch}:item))}/>)}</div>}{error?<p className="py-8 text-center text-[var(--danger)]">{error}</p>:null}<div ref={sentinel} className="h-8" aria-hidden/>{loading&&items.length?<p className="meta-text py-4 text-center">Loading more art…</p>:null}{!loading&&!items.length&&!error?<p className="meta-text py-20 text-center">No published artwork matches these filters.</p>:null}</main>
}
