"use client";

import type { ExploreArtwork } from "@artclub/models";
import { createNetworkApiClient } from "@artclub/api-client";
import Link from "next/link";
import { FormEvent, useCallback, useEffect, useRef, useState } from "react";
import { ActionIcon } from "@/components/icons/ActionIcon";
import { trackNetwork } from "@/lib/client/network-analytics";

const api=createNetworkApiClient();

function ArtworkCard({artwork,onPatch}:{artwork:ExploreArtwork;onPatch:(patch:Partial<ExploreArtwork>)=>void}){
  const ref=useRef<HTMLElement>(null);const impressed=useRef(false);
  useEffect(()=>{const node=ref.current;if(!node)return;const observer=new IntersectionObserver(entries=>{if(entries[0]?.isIntersecting&&entries[0].intersectionRatio>=.5&&!impressed.current){impressed.current=true;trackNetwork("explore_artwork_impression",{canonicalProductId:artwork.id})}},{threshold:.5});observer.observe(node);return()=>observer.disconnect()},[artwork.id]);
  async function action(kind:"like"|"save"){const active=kind==="like"?artwork.liked:artwork.saved;onPatch({[kind==="like"?"liked":"saved"]:!active,...(kind==="like"?{likeCount:Math.max(0,artwork.likeCount+(active?-1:1))}:{})});try{await api.request(`/artworks/${artwork.id}/${kind}`,{method:active?"DELETE":"POST"});trackNetwork(kind==="like"?"explore_artwork_like":"explore_artwork_save",{canonicalProductId:artwork.id})}catch{onPatch({[kind==="like"?"liked":"saved"]:active,...(kind==="like"?{likeCount:artwork.likeCount}:{})})}}
  async function share(){const url=`${location.origin}/explore-art/${artwork.id}`;if(navigator.share)await navigator.share({title:artwork.title,url});else await navigator.clipboard.writeText(url);trackNetwork("explore_artwork_share",{canonicalProductId:artwork.id})}
  return <article ref={ref} className="mb-3 break-inside-avoid overflow-hidden rounded-xl bg-[var(--surface-muted)]"><Link href={`/explore-art/${artwork.id}`} onClick={()=>trackNetwork("explore_artwork_click",{canonicalProductId:artwork.id})} className="block"><img src={artwork.imageUrl} alt={artwork.title} loading="lazy" decoding="async" width={artwork.width||undefined} height={artwork.height||undefined} sizes="(max-width: 767px) 50vw, (max-width: 1279px) 33vw, 25vw" style={artwork.width&&artwork.height?{aspectRatio:`${artwork.width}/${artwork.height}`}:{}} className="h-auto w-full object-cover"/></Link><div className="p-2.5"><Link href={`/explore-art/${artwork.id}`} className="block truncate text-sm font-medium">{artwork.title}</Link><Link href={`/artist/${artwork.artist.slug}`} onClick={()=>trackNetwork("explore_artist_click",{canonicalProductId:artwork.id})} className="meta-text block truncate">{artwork.artist.displayName}</Link><div className="mt-1 flex items-center"><button type="button" onClick={()=>void action("like")} aria-label={artwork.liked?"Unlike artwork":"Like artwork"} title={artwork.liked?"Unlike":"Like"} className={`grid h-9 w-9 place-items-center ${artwork.liked?"text-[var(--text)]":"text-[var(--text-muted)]"}`}><ActionIcon name="like" className="h-4 w-4" filled={artwork.liked}/></button><button type="button" onClick={()=>void action("save")} aria-label={artwork.saved?"Remove saved artwork":"Save artwork"} title={artwork.saved?"Unsave":"Save"} className={`grid h-9 w-9 place-items-center ${artwork.saved?"text-[var(--text)]":"text-[var(--text-muted)]"}`}><ActionIcon name="save" className="h-4 w-4" filled={artwork.saved}/></button><button type="button" onClick={()=>void share()} aria-label="Share artwork" title="Share" className="grid h-9 w-9 place-items-center text-[var(--text-muted)]"><ActionIcon name="share" className="h-4 w-4"/></button>{artwork.shopUrl?<a href={artwork.shopUrl} target="_blank" rel="noreferrer" onClick={()=>trackNetwork("explore_shop_click",{canonicalProductId:artwork.id})} className="ml-auto text-xs font-medium">Shop</a>:null}</div></div></article>;
}

export function ExploreArtClient(){
  const[items,setItems]=useState<ExploreArtwork[]>([]);const[next,setNext]=useState<string|null>(null);const[facets,setFacets]=useState<string[]>([]);const[category,setCategory]=useState("All");const[sort,setSort]=useState<"recent"|"popular">("recent");const[query,setQuery]=useState("");const[submittedQuery,setSubmittedQuery]=useState("");const[loading,setLoading]=useState(false);const[error,setError]=useState("");const sentinel=useRef<HTMLDivElement>(null);const loadingRef=useRef(false);const requestVersion=useRef(0);
  const load=useCallback(async(cursor?:string,version=requestVersion.current)=>{if(loadingRef.current)return;loadingRef.current=true;setLoading(true);setError("");try{const data=await api.exploreArt({cursor,q:submittedQuery||undefined,category:category==="All"?undefined:category,sort});if(version!==requestVersion.current)return;setItems(current=>cursor?[...current,...data.items.filter(item=>!current.some(existing=>existing.id===item.id))]:data.items);setNext(data.nextCursor);setFacets(data.facets)}catch{if(version===requestVersion.current)setError("Explore Art could not be loaded.")}finally{loadingRef.current=false;if(version===requestVersion.current)setLoading(false)}},[category,sort,submittedQuery]);
  useEffect(()=>{requestVersion.current+=1;loadingRef.current=false;setItems([]);setNext(null);void load(undefined,requestVersion.current);trackNetwork("explore_view")},[load]);
  useEffect(()=>{const node=sentinel.current;if(!node)return;const observer=new IntersectionObserver(entries=>{if(entries[0]?.isIntersecting&&next&&!loadingRef.current)void load(next)},{rootMargin:"600px"});observer.observe(node);return()=>observer.disconnect()},[load,next]);
  function search(event:FormEvent){event.preventDefault();setSubmittedQuery(query.trim())}
  function choose(value:string){setCategory(value);trackNetwork("explore_filter_changed",{filter:value})}
  return <main className="app-page max-w-none"><header className="mb-4 flex flex-col gap-3 lg:mb-7 lg:flex-row lg:items-end lg:justify-between"><h1 className="page-heading hidden lg:block">Explore Art</h1><form onSubmit={search} className="flex gap-2"><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search artworks" aria-label="Search artworks" className="control min-w-0 flex-1 lg:w-72"/><button className="secondary-action">Search</button></form></header><div className="mb-4 flex flex-wrap items-center justify-between gap-2 lg:mb-6"><div className="flex flex-wrap gap-2">{["All",...facets].map(value=><button key={value} onClick={()=>choose(value)} className={category===value?"primary-action !min-h-9 !px-3":"secondary-action !min-h-9 !px-3"}>{value}</button>)}</div><select value={sort} onChange={event=>{setSort(event.target.value as "recent"|"popular");trackNetwork("explore_filter_changed",{sort:event.target.value})}} className="control min-h-9 py-1" aria-label="Sort artworks"><option value="recent">Recent</option><option value="popular">Popular</option></select></div>{!items.length&&loading?<div className="columns-2 gap-2 md:columns-3 md:gap-3 xl:columns-4 2xl:columns-5">{Array.from({length:12},(_,index)=><div key={index} className={`mb-3 animate-pulse break-inside-avoid rounded-xl bg-[var(--surface-muted)] ${index%3===0?"h-72":"h-52"}`}/>)}</div>:<div className="columns-2 gap-2 md:columns-3 md:gap-3 xl:columns-4 2xl:columns-5">{items.map(artwork=><ArtworkCard key={artwork.id} artwork={artwork} onPatch={patch=>setItems(current=>current.map(item=>item.id===artwork.id?{...item,...patch}:item))}/>)}</div>}{error?<p className="py-8 text-center text-[var(--danger)]">{error}</p>:null}<div ref={sentinel} className="h-8" aria-hidden/>{loading&&items.length?<p className="meta-text py-4 text-center">Loading more art…</p>:null}{!loading&&!items.length&&!error?<p className="meta-text py-20 text-center">No published artwork matches these filters.</p>:null}</main>;
}
