"use client";

import { createNetworkApiClient } from "@artclub/api-client";
import Link from "next/link";
import { FormEvent, useCallback, useEffect, useRef, useState } from "react";
import { useSearchParams } from "next/navigation";

import { ImageUpload } from "@/components/forms/ImageUpload";
import { FeedVideo } from "@/components/media/FeedVideo";
import { EventFeedCard } from "@/components/network/EventFeedCard";
import { trackNetwork } from "@/lib/client/network-analytics";

const api = createNetworkApiClient();
type Medium = { url:string; type:"image"|"video"; storageKey?:string; provider?:"s3"; mimeType?:string; sizeBytes?:number; width?:number; height?:number; duration?:number; posterStorageKey?:string; posterUrl?:string };
type Post = { id:string; text:string; media:Medium[]; likeCount:number; commentCount:number; liked:boolean; saved:boolean; mine:boolean; createdAt:string; author?:{slug:string;displayName:string;username:string;profileImageUrl:string} };
type Artwork = { id:string; title:string; imageUrl:string; offering:string; priceLabel:string; shopUrl:string; liked:boolean; saved:boolean; likeCount:number };
type Item = {kind:"post";id:string;sortDate:string;post:Post}|{kind:"artwork";id:string;sortDate:string;artwork:Artwork;artist:any}|{kind:"event";id:string;sortDate:string;event:any};

async function inspectVideo(file: File) {
  return new Promise<{width:number;height:number;duration:number;poster?:File}>((resolve,reject) => {
    const video=document.createElement("video");const url=URL.createObjectURL(file);video.preload="metadata";video.muted=true;video.playsInline=true;
    video.onloadedmetadata=()=>{const finish=()=>{const canvas=document.createElement("canvas");canvas.width=Math.min(video.videoWidth,1280);canvas.height=Math.round(canvas.width*(video.videoHeight/video.videoWidth));canvas.getContext("2d")?.drawImage(video,0,0,canvas.width,canvas.height);canvas.toBlob(blob=>{URL.revokeObjectURL(url);resolve({width:video.videoWidth,height:video.videoHeight,duration:video.duration,...(blob?{poster:new File([blob],"poster.jpg",{type:"image/jpeg"})}:{})})},"image/jpeg",.82)};video.onseeked=finish;video.currentTime=Math.min(.1,Math.max(0,video.duration/10))};
    video.onerror=()=>{URL.revokeObjectURL(url);reject(new Error("invalid_video_data"))};video.src=url;
  });
}

function PostCard({post,onAction,onComment,onEdit,onRemove}:{post:Post;onAction:(key:"like"|"save")=>void;onComment:()=>void;onEdit:()=>void;onRemove:()=>void}) {
  return <article className="border-b border-[var(--divider)] py-7">
    <header className="flex items-center gap-3">{post.author?.profileImageUrl?<img src={post.author.profileImageUrl} alt="" className="h-10 w-10 rounded-full object-cover"/>:<span className="h-10 w-10 rounded-full bg-[var(--surface-soft)]"/>}<div><Link href={`/profile/${post.author?.slug}`} className="font-medium">{post.author?.displayName}</Link><p className="text-xs text-[var(--text-faint)]">@{post.author?.username}</p></div></header>
    {post.text?<p className="whitespace-pre-wrap py-4 leading-7">{post.text}</p>:null}
    <div className="space-y-3">{post.media.map((medium,index)=>medium.type==="image"?<img key={index} src={medium.url} alt="Post media" loading="lazy" className="max-h-[46rem] w-full rounded-xl object-cover"/>:<FeedVideo key={index} src={medium.url} poster={medium.posterUrl} width={medium.width} height={medium.height} duration={medium.duration} analyticsId={post.id}/>)}</div>
    <footer className="mt-4 flex flex-wrap gap-5 text-sm text-[var(--text-muted)]"><button onClick={()=>onAction("like")}>{post.liked?"Liked":"Like"} {post.likeCount}</button><button onClick={onComment}>Comment {post.commentCount}</button><button onClick={()=>onAction("save")}>{post.saved?"Saved":"Save"}</button><button onClick={()=>navigator.share?.({url:`${location.origin}/feed?post=${post.id}`})}>Share</button>{post.mine?<><button onClick={onEdit}>Edit</button><button onClick={onRemove} className="text-[var(--danger)]">Delete</button></>:null}</footer>
  </article>;
}

function ArtworkCard({artwork,artist,onAction}:{artwork:Artwork;artist:any;onAction:(key:"like"|"save")=>void}) {
  return <article className="border-b border-[var(--divider)] py-7"><header className="mb-3 flex justify-between"><Link href={`/profile/${artist.slug}`} className="font-medium">{artist.displayName}</Link><span className="eyebrow">Artwork</span></header>{artwork.imageUrl?<a href={artwork.shopUrl} target="_blank" rel="noreferrer" onClick={()=>trackNetwork("artwork_feed_click",{canonicalProductId:artwork.id})}><img src={artwork.imageUrl} alt={artwork.title} loading="lazy" className="max-h-[46rem] w-full rounded-xl object-cover"/></a>:null}<h2 className="mt-4 text-xl font-medium">{artwork.title}</h2><p className="meta-text">{artwork.offering?.replaceAll("_"," ")} {artwork.priceLabel&&`· ${artwork.priceLabel}`}</p><footer className="mt-4 flex gap-5 text-sm text-[var(--text-muted)]"><button onClick={()=>onAction("like")}>{artwork.liked?"Liked":"Like"} {artwork.likeCount}</button><button onClick={()=>onAction("save")}>{artwork.saved?"Saved":"Save"}</button><a href={artwork.shopUrl} target="_blank" rel="noreferrer">Shop</a></footer></article>;
}

export function FeedClient({createOnly=false}:{createOnly?:boolean}) {
  const params=useSearchParams();const[items,setItems]=useState<Item[]>([]);const[text,setText]=useState("");const[media,setMedia]=useState<Medium[]>([]);const[filter,setFilter]=useState("all");const[busy,setBusy]=useState(false);const[loading,setLoading]=useState(false);const[error,setError]=useState("");const[next,setNext]=useState<string|null>(null);const videoInput=useRef<HTMLInputElement>(null);
  const load=useCallback(async(cursor?:string)=>{setLoading(true);try{const data=await api.request<{items:Item[];nextCursor:string|null}>(`/feed?filter=${filter}${cursor?`&cursor=${encodeURIComponent(cursor)}`:""}`);setItems(value=>cursor?[...value,...data.items]:data.items);setNext(data.nextCursor);setError("")}catch{setError("The feed could not be loaded.")}finally{setLoading(false)}},[filter]);
  useEffect(()=>{if(!createOnly){void load();trackNetwork("feed_view")}},[load,createOnly]);
  async function uploadVideos(files:FileList){setBusy(true);try{for(const file of Array.from(files)){const metadata=await inspectVideo(file);let poster:any;if(metadata.poster){const posterForm=new FormData();posterForm.append("file",metadata.poster);posterForm.append("variant","post");poster=(await api.request<any>("/upload",{method:"POST",body:posterForm})).media}const form=new FormData();form.append("file",file);form.append("variant","post");form.append("width",String(metadata.width));form.append("height",String(metadata.height));form.append("duration",String(metadata.duration));if(poster){form.append("posterStorageKey",poster.storageKey);form.append("posterUrl",poster.url)}const data=await api.request<any>("/upload",{method:"POST",body:form});setMedia(value=>[...value,data.media])}}catch{setError("The video could not be uploaded. Use MP4/H.264 or WebM up to 100 MB.")}finally{setBusy(false)}}
  async function submit(event:FormEvent){event.preventDefault();if(busy)return;setBusy(true);try{const data=await api.request<{item:Item}>("/feed",{method:"POST",body:JSON.stringify({type:params.get("type")==="process"?"process":media[0]?.type||"text",text,media,visibility:"public"})});setText("");setMedia([]);setItems(value=>[data.item,...value]);if(createOnly)location.href="/feed"}catch{setError("Your post could not be published.")}finally{setBusy(false)}}
  async function postAction(post:Post,key:"like"|"save"){const active=key==="like"?post.liked:post.saved;await api.request(`/posts/${post.id}/${key}`,{method:active?"DELETE":"POST"});setItems(value=>value.map(item=>item.kind==="post"&&item.post.id===post.id?{...item,post:{...item.post,[key==="like"?"liked":"saved"]:!active,...(key==="like"?{likeCount:Math.max(0,item.post.likeCount+(active?-1:1))}:{})}}:item))}
  async function artworkAction(artwork:Artwork,key:"like"|"save"){const active=key==="like"?artwork.liked:artwork.saved;await api.request(`/artworks/${artwork.id}/${key}`,{method:active?"DELETE":"POST"});setItems(value=>value.map(item=>item.kind==="artwork"&&item.artwork.id===artwork.id?{...item,artwork:{...item.artwork,[key==="like"?"liked":"saved"]:!active,...(key==="like"?{likeCount:Math.max(0,item.artwork.likeCount+(active?-1:1))}:{})}}:item))}
  async function comment(post:Post){const value=prompt("Comment");if(!value)return;await api.request(`/posts/${post.id}/comments`,{method:"POST",body:JSON.stringify({text:value})})}
  async function edit(post:Post){const value=prompt("Edit post",post.text);if(value===null)return;await api.request(`/posts/${post.id}`,{method:"PATCH",body:JSON.stringify({text:value})});void load()}
  async function remove(post:Post){if(confirm("Delete this post?")){await api.request(`/posts/${post.id}`,{method:"DELETE"});setItems(current=>current.filter(item=>item.kind!=="post"||item.post.id!==post.id))}}
  const images=media.filter(item=>item.type==="image");
  return <main className="app-page max-w-3xl">
    {!createOnly?<><header><h1 className="page-heading">Feed</h1><p className="meta-text mt-2">Art, ideas and events from your network.</p></header><nav className="quiet-tabs mt-6">{[["all","All"],["posts","Posts"],["artworks","Artworks"],["events","Events"],["following","Following"]].map(([key,label])=><button key={key} className="quiet-tab" aria-selected={filter===key} onClick={()=>setFilter(key)}>{label}</button>)}</nav></>:null}
    <form onSubmit={submit} className="border-b border-[var(--divider)] py-6"><textarea value={text} onChange={event=>setText(event.target.value)} rows={createOnly?8:3} maxLength={5000} placeholder={params.get("type")==="process"?"Show your process…":"Share something with the art world…"} className="w-full resize-none bg-transparent text-lg leading-7 outline-none"/><ImageUpload label="Post images" variant="post" multiple maxItems={10} items={images} onChange={nextImages=>setMedia([...media.filter(item=>item.type==="video"),...nextImages.map(item=>({...item,type:"image" as const}))])} onUploadingChange={setBusy}/>{media.filter(item=>item.type==="video").map((item,index)=><div className="mt-3" key={item.storageKey||index}><FeedVideo src={item.url} poster={item.posterUrl} width={item.width} height={item.height} duration={item.duration}/><button type="button" className="text-action mt-2" onClick={()=>setMedia(current=>current.filter(value=>value!==item))}>Remove video</button></div>)}<div className="mt-4 flex justify-between"><div><input ref={videoInput} className="hidden" type="file" accept="video/mp4,video/webm,video/quicktime" onChange={event=>event.target.files&&void uploadVideos(event.target.files)}/><button type="button" disabled={busy} onClick={()=>videoInput.current?.click()} className="secondary-action">Add video</button></div><button disabled={busy||(!text.trim()&&!media.length)} className="primary-action disabled:opacity-40">{busy?"Working…":"Post"}</button></div></form>
    {error?<p className="my-4 text-sm text-[var(--danger)]">{error}</p>:null}{!createOnly&&loading&&!items.length?[1,2,3].map(value=><div key={value} className="h-64 animate-pulse border-b border-[var(--divider)] bg-[var(--surface-soft)]"/>):null}
    {!createOnly?items.map(item=>item.kind==="event"?<EventFeedCard key={item.id} initial={item.event}/>:item.kind==="post"?<PostCard key={item.id} post={item.post} onAction={key=>void postAction(item.post,key)} onComment={()=>void comment(item.post)} onEdit={()=>void edit(item.post)} onRemove={()=>void remove(item.post)}/>:<ArtworkCard key={item.id} artwork={item.artwork} artist={item.artist} onAction={key=>void artworkAction(item.artwork,key)}/>):null}
    {!createOnly&&next?<button disabled={loading} onClick={()=>void load(next)} className="secondary-action mt-6 w-full">{loading?"Loading…":"Load more"}</button>:null}
  </main>;
}
