"use client";
import {createNetworkApiClient} from "@artclub/api-client";
import {useEffect,useRef,useState} from "react";
const api=createNetworkApiClient();
const roles=[
  {value:"artist",title:"Artist",description:"Show artworks, share your process, create events and receive donations."},
  {value:"art_enthusiast",title:"Collector / Art Enthusiast",description:"Discover artists, collect art and become part of the community."},
  {value:"gallery",title:"Gallery",description:"Present artists, exhibitions and gallery events."},
  {value:"event_series",title:"Event Organizer",description:"Publish events, invite artists and build a community."},
  {value:"curator",title:"Curator",description:"Present artistic positions, selections and projects."},
  {value:"institution",title:"Institution",description:"Represent a museum, foundation or cultural institution."},
] as const;
export function RoleSelectionClient(){const[selected,setSelected]=useState("");const[loading,setLoading]=useState(true);const[busy,setBusy]=useState(false);const[error,setError]=useState("");const submitting=useRef(false);useEffect(()=>{api.request<any>("/onboarding/role").then(data=>{if(data.autoDetected){location.replace("/onboarding/profile");return}if(data.profileType)setSelected(data.profileType)}).catch(()=>setError("Your account type could not be loaded.")).finally(()=>setLoading(false))},[]);async function confirm(){if(!selected||submitting.current)return;submitting.current=true;setBusy(true);setError("");try{const data=await api.request<any>("/onboarding/role",{method:"POST",body:JSON.stringify({profileType:selected})});location.href=data.next||"/onboarding/profile"}catch{setError("Your account type could not be saved.");submitting.current=false;setBusy(false)}}return <main className="mx-auto max-w-4xl px-0 py-7 sm:px-4"><p className="eyebrow">ARTCLUB – The network of art</p><h1 className="mt-2 text-4xl font-semibold tracking-tight">How do you participate in the art world?</h1>{loading?<div className="mt-6 grid gap-3 sm:grid-cols-2">{roles.map(role=><div key={role.value} className="h-32 animate-pulse rounded-2xl bg-[var(--surface-muted)]"/>)}</div>:<div className="mt-6 grid gap-3 sm:grid-cols-2">{roles.map(role=><button key={role.value} type="button" onClick={()=>setSelected(role.value)} aria-pressed={selected===role.value} className={`rounded-2xl border p-4 text-left transition ${selected===role.value?"border-[var(--primary)] bg-[var(--primary)] text-[var(--primary-foreground)]":"border-[var(--border)] hover:border-[var(--text-muted)]"}`}><span className="text-xl font-semibold">{role.title}</span><span className={`mt-1 block text-sm leading-6 ${selected===role.value?"text-inherit opacity-80":"text-[var(--text-muted)]"}`}>{role.description}</span></button>)}</div>}{error&&<p role="alert" className="mt-5 text-sm text-[var(--danger)]">{error}</p>}<button type="button" disabled={!selected||busy||loading} onClick={()=>void confirm()} className="primary-action mt-6 disabled:opacity-40">{busy?"Saving…":"Confirm account type"}</button></main>}
