"use client";
import {createNetworkApiClient} from "@artclub/api-client";
import {useEffect,useRef,useState} from "react";
const api=createNetworkApiClient();
const roles=[
  {value:"artist",title:"Artist",description:"Show artworks, share your process, create events and receive donations."},
  {value:"art_enthusiast",title:"Collector / Art Enthusiast",description:"Discover artists, collect art and become part of the community."},
  {value:"gallery",title:"Gallery",description:"Present artists, exhibitions and gallery events."},
  {value:"event_series",title:"Event Organizer",description:"Publish events, invite artists and build a community."},
  {value:"curator",title:"Curator",description:"Present artistic positions, selections and projects."},
  {value:"institution",title:"Institution",description:"Represent a museum, foundation or cultural institution."},
] as const;
export function RoleSelectionClient(){const[selected,setSelected]=useState("");const[loading,setLoading]=useState(true);const[busy,setBusy]=useState(false);const[error,setError]=useState("");const submitting=useRef(false);useEffect(()=>{api.request<any>("/onboarding/role").then(data=>{if(data.autoDetected){location.replace("/onboarding/profile");return}if(data.profileType)setSelected(data.profileType)}).catch(()=>setError("Your account type could not be loaded.")).finally(()=>setLoading(false))},[]);async function confirm(){if(!selected||submitting.current)return;submitting.current=true;setBusy(true);setError("");try{const data=await api.request<any>("/onboarding/role",{method:"POST",body:JSON.stringify({profileType:selected})});location.href=data.next||"/onboarding/profile"}catch{setError("Your account type could not be saved.");submitting.current=false;setBusy(false)}}return <main className="mx-auto max-w-4xl px-5 py-10"><p className="text-sm uppercase tracking-widest text-neutral-400">ARTCLUB Network</p><h1 className="mt-2 text-4xl font-semibold tracking-tight">How do you participate in the art world?</h1><p className="mt-3 text-neutral-500">Choose the account type that best describes you. You can review it later in Settings.</p>{loading?<div className="mt-8 grid gap-4 sm:grid-cols-2">{roles.map(role=><div key={role.value} className="h-36 animate-pulse rounded-2xl bg-neutral-100"/>)}</div>:<div className="mt-8 grid gap-4 sm:grid-cols-2">{roles.map(role=><button key={role.value} type="button" onClick={()=>setSelected(role.value)} aria-pressed={selected===role.value} className={`rounded-2xl border p-5 text-left transition ${selected===role.value?"border-neutral-950 bg-neutral-950 text-white dark:border-white dark:bg-white dark:text-black":"border-neutral-200 hover:border-neutral-500 dark:border-neutral-800"}`}><span className="text-xl font-semibold">{role.title}</span><span className={`mt-2 block text-sm leading-6 ${selected===role.value?"text-inherit opacity-75":"text-neutral-500"}`}>{role.description}</span></button>)}</div>}{error&&<p role="alert" className="mt-5 text-sm text-red-600">{error}</p>}<button type="button" disabled={!selected||busy||loading} onClick={()=>void confirm()} className="mt-8 rounded-full bg-neutral-950 px-7 py-3 text-white disabled:opacity-40 dark:bg-white dark:text-black">{busy?"Saving…":"Confirm account type"}</button></main>}
