import { Image } from "expo-image";
import { useLocalSearchParams, useRouter } from "expo-router";
import { useCallback, useEffect, useState } from "react";
import { Linking, Share, Text, View } from "react-native";

import { track } from "../../src/analytics";
import { useAuth } from "../../src/auth";
import { useTheme } from "../../src/theme";
import { Avatar, Button, ErrorState, Field, Loading, Page, Section } from "../../src/ui";

export default function PublicProfile() {
  const { slug } = useLocalSearchParams<{ slug: string }>(); const { api } = useAuth(); const { colors } = useTheme(); const router = useRouter();
  const [data, setData] = useState<any>(null); const [error, setError] = useState(""); const [requestOpen, setRequestOpen] = useState(false); const [requestText, setRequestText] = useState("");
  const load = useCallback(async () => { try { const result = await api.request(`/profiles/${slug}`); setData(result); setError(""); void track(api, "profile_view", { profileId: result.profile.id }); } catch { setError("This profile is not available."); } }, [api, slug]);
  useEffect(() => { void load(); }, [load]);
  async function connect() { await api.request("/connections", { method: "POST", body: JSON.stringify({ profileId: data.profile.id }) }); void track(api, "connection_request_sent", { profileId: data.profile.id }); await load(); }
  async function follow() { const next = !data.relationship.following; await api.request(`/profiles/${data.profile.id}/follow`, { method: next ? "POST" : "DELETE" }); setData((value: any) => ({ ...value, relationship: { ...value.relationship, following: next } })); void track(api, next ? "profile_follow" : "profile_unfollow", { profileId: data.profile.id }); }
  async function appreciate() { const next = !data.relationship.liked; await api.request(`/profiles/${data.profile.id}/like`, { method: next ? "POST" : "DELETE" }); setData((value: any) => ({ ...value, relationship: { ...value.relationship, liked: next } })); }
  async function message() { const result = await api.request("/conversations", { method: "POST", body: JSON.stringify({ profileId: data.profile.id }) }); router.push(`/messages/${result.conversation.id}` as never); }
  async function requestMessage() { await api.request("/message-requests", { method: "POST", body: JSON.stringify({ profileId: data.profile.id, text: requestText }) }); setRequestOpen(false); setRequestText(""); void track(api, "message_request_sent", { profileId: data.profile.id }); await load(); }
  if (!data && !error) return <Loading/>; if (!data) return <ErrorState message={error} retry={load}/>;
  const { profile, relationship } = data;
  return <Page>{profile.coverImageUrl ? <Image source={profile.coverImageUrl} style={{ width: "100%", aspectRatio: 16 / 7, borderRadius: 4 }} contentFit="cover"/> : <View style={{ width: "100%", aspectRatio: 16 / 7, borderRadius: 4, backgroundColor: colors.surfaceMuted }}/>}<View style={{ alignItems: "center", gap: 6, marginTop: -40 }}><Avatar profile={profile} size={82}/><Text style={{ color: colors.text, fontSize: 27, fontWeight: "600" }}>{profile.displayName}</Text><Text style={{ color: colors.textMuted }}>@{profile.username} · {profile.profileType.replaceAll("_", " ")}</Text><Text style={{ color: colors.textMuted }}>{[profile.city, profile.country].filter(Boolean).join(", ")}</Text></View>{!relationship.mine ? <><View style={{ flexDirection: "row", gap: 8 }}><View style={{ flex: 1 }}>{relationship.state === "connected" ? <Button label="Message" onPress={() => void message()}/> : <Button label={relationship.state === "outgoing_pending" ? "Requested" : "Connect"} disabled={relationship.state === "outgoing_pending"} onPress={() => void connect()}/>}</View><View style={{ flex: 1 }}><Button label={relationship.following ? "Following" : "Follow"} variant="secondary" onPress={() => void follow()}/></View></View><View style={{ flexDirection: "row", gap: 8 }}><View style={{ flex: 1 }}><Button label={relationship.liked ? "Appreciated" : "Appreciate"} variant="secondary" icon="heart-outline" onPress={() => void appreciate()}/></View>{relationship.state !== "connected" ? <View style={{ flex: 1 }}><Button label="Message request" variant="secondary" onPress={() => setRequestOpen((value) => !value)}/></View> : null}<Button label="Share" variant="text" icon="share-outline" onPress={() => void Share.share({ message: `https://network.artclub.wtf/artist/${profile.slug}` })}/></View>{requestOpen ? <Section title="Message request"><Field label="Introduction" value={requestText} onChangeText={setRequestText} maxLength={100} multiline placeholder="Introduce yourself in up to 100 characters."/><Text style={{ color: colors.textMuted, fontSize: 12 }}>{requestText.length}/100</Text><Button label="Send request" onPress={() => void requestMessage()} disabled={!requestText.trim()}/></Section> : null}</> : <Button label="Edit profile" onPress={() => router.push("/profile/edit")}/>}<Section title="About"><Text style={{ color: colors.text, lineHeight: 22 }}>{profile.bio || "No biography yet."}</Text>{profile.disciplines?.length ? <Text style={{ color: colors.textMuted }}>{profile.disciplines.join(" · ")}</Text> : null}</Section>{profile.website || profile.instagram ? <Section title="Links">{profile.website ? <Button label="Website" variant="secondary" onPress={() => void Linking.openURL(profile.website)}/> : null}{profile.instagram ? <Button label="Instagram" variant="secondary" onPress={() => void Linking.openURL(profile.instagram.startsWith("http") ? profile.instagram : `https://instagram.com/${profile.instagram.replace(/^@/, "")}`)}/> : null}</Section> : null}</Page>;
}
