import { networkMessageInputSchema } from "@artclub/models";
import { Types } from "mongoose";

import { mobileError, mobileNetworkContext, serializeMobileProfile } from "@/lib/mobileNetwork";
import { ConnectionModel, NetworkConversationModel, NetworkMessageModel, NetworkNotificationModel } from "@/models/Network";

export async function GET(req: Request, { params }: { params: Promise<{ id: string }> }) {
  const auth = await mobileNetworkContext(req); if (!auth.ok) return auth.response; const { id } = await params; if (!Types.ObjectId.isValid(id)) return mobileError("invalid_conversation_id");
  const conversation = await NetworkConversationModel.findOne({ _id: id, participantProfileIds: auth.profile!._id }).populate("participantProfileIds", "displayName username slug profileImageUrl profileType city country").lean(); if (!conversation) return mobileError("conversation_not_found", 404);
  const cursor = new URL(req.url).searchParams.get("cursor"); const query: any = { conversationId: id, deletedAt: { $exists: false } }; if (cursor && Types.ObjectId.isValid(cursor)) query._id = { $lt: cursor }; const rows = await NetworkMessageModel.find(query).sort({ _id: -1 }).limit(51).lean(); const page = rows.slice(0, 50); const other = (conversation.participantProfileIds as any[]).find((value: any) => String(value._id) !== String(auth.profile!._id));
  return Response.json({ ok: true, participant: other ? serializeMobileProfile(other) : null, muted: (conversation.mutedBy || []).some((value) => String(value) === String(auth.profile!._id)), messages: page.reverse().map((message) => ({ id: String(message._id), text: message.text || "", media: message.media || [], mine: String(message.senderProfileId) === String(auth.profile!._id), read: message.readBy.some((value) => String(value) !== String(message.senderProfileId)), createdAt: message.createdAt })), nextCursor: rows.length > 50 ? String(rows[49]._id) : null });
}
export async function POST(req: Request, context: { params: Promise<{ id: string }> }) {
  const auth = await mobileNetworkContext(req); if (!auth.ok) return auth.response; const { id } = await context.params; const parsed = networkMessageInputSchema.safeParse(await req.json().catch(() => null)); if (!parsed.success) return mobileError("invalid_message", 400, parsed.error.flatten());
  const conversation = await NetworkConversationModel.findOne({ _id: id, participantProfileIds: auth.profile!._id }); if (!conversation) return mobileError("conversation_not_found", 404); const recipientId = conversation.participantProfileIds.find((value) => String(value) !== String(auth.profile!._id)); const connected = recipientId && await ConnectionModel.exists({ status: "accepted", $or: [{ requesterProfileId: auth.profile!._id, recipientProfileId: recipientId }, { requesterProfileId: recipientId, recipientProfileId: auth.profile!._id }] }); if (!connected) return mobileError("messaging_not_allowed", 403);
  const message = await NetworkMessageModel.create({ conversationId: conversation._id, senderProfileId: auth.profile!._id, text: parsed.data.text, media: parsed.data.media, readBy: [auth.profile!._id] }); conversation.lastMessageAt = message.createdAt; conversation.lastMessagePreview = parsed.data.text.slice(0, 160) || "Attachment"; await conversation.save(); await NetworkNotificationModel.create({ recipientProfileId: recipientId, actorProfileId: auth.profile!._id, type: "new_message", targetType: "conversation", targetId: conversation._id }); return Response.json({ ok: true, message: { id: String(message._id), text: message.text || "", media: message.media || [], mine: true, read: false, createdAt: message.createdAt } }, { status: 201 });
}
