"use client";

import { useEffect, useRef, useState } from "react";
import { trackNetwork } from "@/lib/client/network-analytics";

type FeedVideoProps={src:string;poster?:string;width?:number;height?:number;duration?:number;analyticsId?:string};

export function FeedVideo({src,poster,width,height,duration,analyticsId}:FeedVideoProps){
  const videoRef=useRef<HTMLVideoElement>(null);const rootRef=useRef<HTMLDivElement>(null);const[playing,setPlaying]=useState(false);const[muted,setMuted]=useState(true);const[knownDuration,setKnownDuration]=useState(duration||0);const impressed=useRef(false);
  useEffect(()=>{const video=videoRef.current;const root=rootRef.current;if(!video||!root)return;const observer=new IntersectionObserver(entries=>{const visible=entries[0]?.isIntersecting&&entries[0].intersectionRatio>=.5;if(visible&&!impressed.current){impressed.current=true;trackNetwork("video_impression",analyticsId?{postId:analyticsId}:{})}if(!visible&&!video.paused)video.pause()},{threshold:[0,.5]});observer.observe(root);const pauseOther=(event:Event)=>{if((event as CustomEvent).detail!==video&&!video.paused)video.pause()};window.addEventListener("artclub-video-play",pauseOther);return()=>{observer.disconnect();window.removeEventListener("artclub-video-play",pauseOther)}},[analyticsId]);
  async function toggle(){const video=videoRef.current;if(!video)return;if(video.paused){window.dispatchEvent(new CustomEvent("artclub-video-play",{detail:video}));await video.play();trackNetwork("video_play",analyticsId?{postId:analyticsId}:{})}else{video.pause();trackNetwork("video_pause",analyticsId?{postId:analyticsId}:{})}}
  function toggleMute(){const video=videoRef.current;if(!video)return;video.muted=!video.muted;setMuted(video.muted);if(!video.muted)trackNetwork("video_unmute",analyticsId?{postId:analyticsId}:{})}
  const ratio=width&&height?`${width}/${height}`:"16/9";const label=knownDuration?`${Math.floor(knownDuration/60)}:${String(Math.floor(knownDuration%60)).padStart(2,"0")}`:"";
  return <div ref={rootRef} className="relative w-full overflow-hidden rounded-xl bg-[var(--surface-soft)]" style={{aspectRatio:ratio,maxHeight:"min(72vh,46rem)"}}><video ref={videoRef} src={src} poster={poster} playsInline muted preload="metadata" onLoadedMetadata={event=>setKnownDuration(event.currentTarget.duration||0)} onPlay={()=>setPlaying(true)} onPause={()=>setPlaying(false)} onEnded={()=>{setPlaying(false);trackNetwork("video_complete",analyticsId?{postId:analyticsId}:{})}} className="h-full w-full object-contain"/><button type="button" onClick={()=>void toggle()} aria-label={playing?"Pause video":"Play video"} className="absolute inset-0 grid place-items-center"><span className={`grid h-14 w-14 place-items-center rounded-full bg-black/55 text-xl text-white backdrop-blur transition-opacity ${playing?"opacity-0 hover:opacity-100 focus:opacity-100":"opacity-100"}`}>{playing?"Ⅱ":"▶"}</span></button><div className="pointer-events-none absolute inset-x-0 bottom-0 flex items-center justify-between bg-gradient-to-t from-black/65 to-transparent p-3 pt-8 text-xs text-white"><button type="button" onClick={toggleMute} className="pointer-events-auto" aria-label={muted?"Unmute video":"Mute video"}>{muted?"Muted":"Sound on"}</button><span>{label}</span></div></div>
}
