"use client";

import { useEffect, useRef, useState } from "react";
import { trackNetwork } from "@/lib/client/network-analytics";
import { ActionIcon } from "@/components/icons/ActionIcon";

type FeedVideoProps={src:string;poster?:string;width?:number;height?:number;duration?:number;analyticsId?:string};

export function FeedVideo({src,poster,width,height,duration,analyticsId}:FeedVideoProps){
  const videoRef=useRef<HTMLVideoElement>(null);const rootRef=useRef<HTMLDivElement>(null);const[playing,setPlaying]=useState(false);const[muted,setMuted]=useState(false);const[knownDuration,setKnownDuration]=useState(duration||0);const[playError,setPlayError]=useState("");const impressed=useRef(false);
  useEffect(()=>{const video=videoRef.current;const root=rootRef.current;if(!video||!root)return;const observer=new IntersectionObserver(entries=>{const visible=entries[0]?.isIntersecting&&entries[0].intersectionRatio>=.5;if(visible&&!impressed.current){impressed.current=true;trackNetwork("video_impression",analyticsId?{postId:analyticsId}:{})}if(!visible&&!video.paused)video.pause()},{threshold:[0,.5]});observer.observe(root);const pauseOther=(event:Event)=>{if((event as CustomEvent).detail!==video&&!video.paused)video.pause()};window.addEventListener("artclub-video-play",pauseOther);return()=>{observer.disconnect();window.removeEventListener("artclub-video-play",pauseOther)}},[analyticsId]);
  async function toggle(){const video=videoRef.current;if(!video)return;if(video.paused){setPlayError("");video.muted=muted;window.dispatchEvent(new CustomEvent("artclub-video-play",{detail:video}));try{await video.play();trackNetwork("video_play",analyticsId?{postId:analyticsId}:{})}catch{setPlayError("Playback was blocked. Tap play again.")}}else{video.pause();trackNetwork("video_pause",analyticsId?{postId:analyticsId}:{})}}
  function toggleMute(){const video=videoRef.current;if(!video)return;video.muted=!video.muted;setMuted(video.muted);sessionStorage.setItem("artclub-video-muted",video.muted?"1":"0");if(!video.muted)trackNetwork("video_unmute",analyticsId?{postId:analyticsId}:{})}
  useEffect(()=>{const preference=sessionStorage.getItem("artclub-video-muted")==="1";setMuted(preference);if(videoRef.current)videoRef.current.muted=preference},[]);
  const label=knownDuration?`${Math.floor(knownDuration/60)}:${String(Math.floor(knownDuration%60)).padStart(2,"0")}`:"";
  return <div ref={rootRef} className="relative aspect-[4/5] w-full overflow-hidden bg-[var(--surface-muted)] sm:rounded-xl"><video ref={videoRef} src={src} poster={poster} playsInline preload="metadata" onLoadedMetadata={event=>setKnownDuration(event.currentTarget.duration||0)} onPlay={()=>setPlaying(true)} onPause={()=>setPlaying(false)} onEnded={()=>{setPlaying(false);trackNetwork("video_complete",analyticsId?{postId:analyticsId}:{})}} className="h-full w-full object-cover"/><button type="button" onClick={()=>void toggle()} aria-label={playing?"Pause video":"Play video with sound"} title={playing?"Pause":"Play"} className="absolute inset-0 grid place-items-center"><span className={`grid h-12 w-12 place-items-center rounded-full bg-black/55 text-white transition-opacity ${playing?"opacity-0 hover:opacity-100 focus:opacity-100":"opacity-100"}`}><ActionIcon name={playing?"pause":"play"} className="h-5 w-5"/></span></button><div className="pointer-events-none absolute inset-x-0 bottom-0 flex items-center justify-between bg-gradient-to-t from-black/65 to-transparent p-3 pt-8 text-xs text-white"><button type="button" onClick={toggleMute} className="pointer-events-auto grid h-9 w-9 place-items-center rounded-full bg-black/35" aria-label={muted?"Unmute video":"Mute video"} title={muted?"Unmute":"Mute"}><ActionIcon name={muted?"muted":"volume"} className="h-5 w-5"/></button><span>{label}</span></div>{playError?<p className="absolute inset-x-3 bottom-12 rounded-lg bg-black/70 p-2 text-center text-xs text-white">{playError}</p>:null}</div>
}
