import { networkProfileTypes } from "@artclub/models";
import { useRouter } from "expo-router";
import { useState } from "react";
import { Pressable, Text, View } from "react-native";
import { useAuth } from "../../src/auth";
import { useTheme } from "../../src/theme";
import { Button, Field, Page } from "../../src/ui";
const roles = networkProfileTypes.filter((role) => !["curator", "institution", "other"].includes(role));
export default function Onboarding() { const { api, user, profile, refreshProfile } = useAuth(); const router = useRouter(); const { colors } = useTheme(); const [role, setRole] = useState(profile?.profileType || "artist"); const [displayName, setDisplayName] = useState(profile?.displayName || user?.name || ""); const [username, setUsername] = useState(profile?.username || ""); const [bio, setBio] = useState(profile?.bio || ""); const [city, setCity] = useState(profile?.city || ""); const [country, setCountry] = useState(profile?.country || ""); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); async function submit() { setBusy(true); setError(""); try { await api.request("/profile", { method: "POST", body: JSON.stringify({ profileType: role, displayName, username, bio, city, country, disciplines: [], interests: [], isPublic: true, allowsMessages: false, donationEnabled: false }) }); await refreshProfile(); router.replace("/home"); } catch (reason) { setError(reason instanceof Error ? reason.message : "Profile setup failed"); } finally { setBusy(false); } } return <Page title="Build your art-world identity" subtitle="Your public and network profile are one identity."><Text style={{ color: colors.text, fontWeight: "600" }}>Role</Text><View style={{ flexDirection: "row", flexWrap: "wrap", gap: 8 }}>{roles.map((item) => <Pressable key={item} onPress={() => setRole(item)} style={{ borderWidth: 1, borderColor: role === item ? colors.text : colors.border, backgroundColor: role === item ? colors.surfaceMuted : colors.surface, borderRadius: 6, paddingHorizontal: 12, paddingVertical: 10 }}><Text style={{ color: colors.text, textTransform: "capitalize" }}>{item.replaceAll("_", " ")}</Text></Pressable>)}</View><Field label="Name" value={displayName} onChangeText={setDisplayName}/><Field label="Username" value={username} onChangeText={(value) => setUsername(value.toLowerCase().replace(/[^a-z0-9._-]/g, ""))} autoCapitalize="none"/><Field label="Bio" value={bio} onChangeText={setBio} multiline/><Field label="City" value={city} onChangeText={setCity}/><Field label="Country" value={country} onChangeText={setCountry}/>{error ? <Text style={{ color: colors.danger }}>{error}</Text> : null}<Button label={busy ? "Saving…" : "Complete profile"} onPress={() => void submit()} disabled={busy || !displayName || username.length < 3}/></Page>; }
