import type { ArtworkCard } from "@artclub/models";
import { Image } from "expo-image";
import { useLocalSearchParams } from "expo-router";
import { useEffect, useState } from "react";
import { Linking, Share, Text } from "react-native";
import { track } from "../../src/analytics";
import { useAuth } from "../../src/auth";
import { useTheme } from "../../src/theme";
import { Button, ErrorState, Loading, Page, Section } from "../../src/ui";
export default function ArtworkDetail() { const { id } = useLocalSearchParams<{ id: string }>(); const { api, baseUrl } = useAuth(); const { colors } = useTheme(); const [artwork, setArtwork] = useState<ArtworkCard | null>(null); const [error, setError] = useState(""); async function load() { try { const response = await fetch(`${baseUrl}/api/mobile/v1/artworks/${encodeURIComponent(id)}`); if (!response.ok) throw new Error(); const data = await response.json(); setArtwork(data.artwork); setError(""); } catch { setError("This artwork could not be loaded."); } } useEffect(() => { void load(); void track(api, "product_view", { artworkId: id }); }, [id]); if (!artwork && !error) return <Loading/>; if (!artwork) return <ErrorState message={error} retry={() => void load()}/>; const shopUrl = `https://artclub.wtf/products/${artwork.handle || ""}`; return <Page>{artwork.images.map((image) => <Image key={image.urlMedium} source={image.urlMedium} style={{ width: "100%", aspectRatio: image.aspectRatio || 4 / 5, borderRadius: 4, backgroundColor: colors.surfaceMuted }} contentFit="cover"/>)}<Text style={{ color: colors.text, fontSize: 29, fontWeight: "600" }}>{artwork.title || "Untitled"}</Text><Text style={{ color: colors.textMuted, fontSize: 17 }}>{artwork.artistName}</Text><Text style={{ color: colors.text }}>{[artwork.widthCm, artwork.heightCm].filter(Boolean).join(" × ")}{artwork.widthCm ? " cm" : ""}{artwork.priceEur ? ` · €${artwork.priceEur.toLocaleString()}` : ""}</Text><Section title="About"><Text style={{ color: colors.text, lineHeight: 22 }}>{artwork.shortDescription || "Shopify is the source of truth for availability and product details."}</Text><Text style={{ color: colors.textMuted }}>{artwork.tags.join(" · ")}</Text></Section><Button label="View in shop" onPress={() => { void track(api, "artwork_shop_click", { artworkId: artwork.id }); void Linking.openURL(shopUrl); }}/><Button label="Share artwork" variant="secondary" icon="share-outline" onPress={() => void Share.share({ message: shopUrl })}/></Page>; }
