import { networkEventInputSchema } from "@artclub/models";
import { requireNetworkApiContext, serializeNetworkProfile } from "@/lib/server/network-context";
import { apiError, validId } from "@/lib/server/network-service";
import { EventRSVPModel, NetworkEventModel } from "@/lib/server/models";

function output(item: any, count: number, attending: boolean, viewer: unknown) { const organizer = item.organizerProfileId && typeof item.organizerProfileId === "object" && "displayName" in item.organizerProfileId ? item.organizerProfileId : null; return { id: item._id.toString(), title: item.title, slug: item.slug, description: item.description || "", coverImageUrl: item.coverImageUrl || "", startAt: item.startAt, endAt: item.endAt, timezone: item.timezone, venueName: item.venueName || "", address: item.address || "", city: item.city || "", country: item.country || "", isOnline: item.isOnline === true, ticketUrl: item.ticketUrl || "", rsvpEnabled: item.rsvpEnabled !== false, capacity: item.capacity, visibility: item.visibility, status: item.status, participantProfileIds: (item.participantProfileIds || []).map(String), organizer: organizer ? serializeNetworkProfile(organizer) : undefined, mine: String(organizer?._id || item.organizerProfileId) === String(viewer), rsvpCount: count, attending }; }
export async function GET(_: Request, { params }: { params: Promise<{ id: string }> }) { const auth = await requireNetworkApiContext(); if (!auth.ok) return auth.response; const { id } = await params; if (!validId(id)) return apiError("invalid_event_id"); const event = await NetworkEventModel.findOne({ _id: id, $or: [{ status: "published", visibility: "public" }, { organizerProfileId: auth.context.profile._id }] }).populate("organizerProfileId", "displayName username slug profileImageUrl profileType isVerified donationEnabled allowsMessages").lean(); if (!event) return apiError("event_not_found", 404); const [count, attending] = await Promise.all([EventRSVPModel.countDocuments({ eventId: id, status: "going" }), EventRSVPModel.exists({ eventId: id, profileId: auth.context.profile._id, status: "going" })]); return Response.json({ ok: true, event: output(event, count, Boolean(attending), auth.context.profile._id) }); }
export async function PATCH(req: Request, { params }: { params: Promise<{ id: string }> }) { const auth = await requireNetworkApiContext(); if (!auth.ok) return auth.response; const { id } = await params; if (!validId(id)) return apiError("invalid_event_id"); const current = await NetworkEventModel.findOne({ _id: id, organizerProfileId: auth.context.profile._id }); if (!current) return apiError("event_not_found", 404); const body = await req.json().catch(() => null); const parsed = networkEventInputSchema.safeParse({ title: current.title, description: current.description || "", startAt: current.startAt, endAt: current.endAt, timezone: current.timezone, venueName: current.venueName || "", address: current.address || "", city: current.city || "", country: current.country || "", isOnline: current.isOnline, ticketUrl: current.ticketUrl || "", rsvpEnabled: current.rsvpEnabled, capacity: current.capacity, visibility: current.visibility, participantProfileIds: current.participantProfileIds.map(String), status: current.status === "published" ? "published" : "draft", ...(body || {}) }); if (!parsed.success) return apiError("invalid_event", 400, parsed.error.flatten()); Object.assign(current, parsed.data); await current.save(); return Response.json({ ok: true, event: output(current, 0, false, auth.context.profile._id) }); }
export async function DELETE(_: Request, { params }: { params: Promise<{ id: string }> }) { const auth = await requireNetworkApiContext(); if (!auth.ok) return auth.response; const { id } = await params; if (!validId(id)) return apiError("invalid_event_id"); const event = await NetworkEventModel.findOne({ _id: id, organizerProfileId: auth.context.profile._id }); if (!event) return apiError("event_not_found", 404); if (event.status === "published") { event.status = "cancelled"; await event.save(); } else await event.deleteOne(); return Response.json({ ok: true }); }
